Mon 23:10

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -275,6 +275,8 @@ jobs:
       - run:
           name: Copy fronted/dist to s3 bucket
           command: |
+            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID2
+            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY2
             aws --version
             # $ aws s3 cp ./dist s3://s3-uda-deploy --recursive \
             # --exclude "*.DS_Store" --acl public-read --cache-control \
@@ -288,15 +290,17 @@ jobs:
       - run:
           name: Copy fronted/dist to s3 bucket
           command: |
+            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID2
+            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY2
             BACKEND_IP=$(aws ec2 describe-instances  \
               --filters Name=tag-key,Values=Name  \
               --query 'Reservations[*].Instances[*].{IP:PublicIpAddress,Name:Tags[?Key==`Name`]|[0].Value}' \
               --output text|grep backend|awk '{print $1}' )
             if curl -s ${BACKEND_IP} | grep -i "status"
             then
-              exit 1
+              exit 0   # OK
             else
-              exit 0
+              exit 1   # Fail
             fi
 
   check-curl-frontend:
@@ -310,9 +314,9 @@ jobs:
             FRONTEND="http://s3-uda-deploy.s3-website-us-east-1.amazonaws.com/#/employees"
             if curl -s ${FRONTEND} | grep -i "Welcome"
             then
-              exit 1
+              exit 0	# OK
             else
-              exit 0
+              exit 1	# Fail
             fi
 
 
