Sun 11:03

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -432,7 +432,8 @@ jobs:
             if curl -s  "http://${BACKEND_IP}:3030/api/status" | grep -i "status"
             then
               #-exit 0   # OK
-            #-else
+              echo "Do not exit - show the new IP"
+            else
               #- exit 1   # Fail
               # Roll back instance
               # Set .env on frontend to the IP in memstash.
@@ -447,8 +448,16 @@ jobs:
               echo "API_URL=http://$BACKEND_IP_NEW:3030" > frontend/.env
               # Show me the change
               echo "frontend/.env:"
-              cat frontend/.env              
+              cat frontend/.env
+              exit 1	# Fail ==> Show evidence the new backend EC2
             fi
+            BACKEND_IP_NEW=$(aws ec2 describe-instances  \
+                --filters Name=tag-key,Values=Name  \
+                --query 'Reservations[*].Instances[*].{IP:PublicIpAddress,Name:Tags[?Key==`Name`]|[0].Value}' \
+                --output text|grep $instance_name|awk '{print $1}' )
+            echo "BACKEND_IP_NEW = $BACKEND_IP_NEW"
+            echo "API_URL=http://$BACKEND_IP_NEW:3030" > frontend/.env
+            
 
   check-curl-frontend:
     docker:
